[tool.poetry]
name = "gram-schmidt"
version = "0.1.0"
description = ""
authors = ["Hiroki Yoda <hyoda365@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^2.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
